version: '3'

services:
  arkham-hq-auth-ui:
    build:
      # Needed to bring the workspace's "pnpm-lock.yaml" in scope
      context: ../../../../
      dockerfile: packages/auth/ui/docker/Dockerfile
    image: arkham-hq-auth-ui
    ports:
      - '3000:3000'
