import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import TrpcProvider from './api/trpc-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Armham HQ Auth',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <TrpcProvider>
      <html lang="en" className="bg-slate-200">
        <body className={inter.className}>{children}</body>
      </html>
    </TrpcProvider>
  )
}
